swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /workspace/{name}:
        get:
            tags:
                - kollap
            summary: createWorkspace kollap
            operationId: kollap#createWorkspace
            parameters:
                - name: name
                  in: path
                  description: test1
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
