swagger: "2.0"
info:
    title: Collaborative Knowledge Platform Backenk service
    description: |4-
        	API for backend service powering Kollap platform.
        	
    version: "1.0"
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /v1/documents:
        post:
            tags:
                - documents
            summary: createDocument documents
            operationId: documents#createDocument
            parameters:
                - name: CreateDocumentRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/DocumentsCreateDocumentRequestBody'
                    required:
                        - title
                        - workspace_id
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Document'
                        required:
                            - id
                            - title
                            - version
                            - content
                            - workspace_id
                            - created_at
            schemes:
                - http
    /v1/documents/{id}:
        get:
            tags:
                - documents
            summary: getDocument documents
            operationId: documents#getDocument
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
                  format: uuid
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Document'
                        required:
                            - id
                            - title
                            - version
                            - content
                            - workspace_id
                            - created_at
            schemes:
                - http
    /v1/workspaces:
        post:
            tags:
                - workspaces
            summary: createWorkspace workspaces
            operationId: workspaces#createWorkspace
            parameters:
                - name: CreateWorkspaceRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/WorkspacesCreateWorkspaceRequestBody'
                    required:
                        - name
                        - owner_id
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Workspace'
                        required:
                            - id
                            - name
                            - owner_id
                            - created_at
            schemes:
                - http
    /v1/workspaces/{id}:
        get:
            tags:
                - workspaces
            summary: getWorkspace workspaces
            operationId: workspaces#getWorkspace
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
                  format: uuid
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Workspace'
                        required:
                            - id
                            - name
                            - owner_id
                            - created_at
            schemes:
                - http
    /v1/workspaces/{id}/documents:
        get:
            tags:
                - workspaces
            summary: getAllWorkspaceDocuments workspaces
            operationId: workspaces#getAllWorkspaceDocuments
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
                  format: uuid
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/WorkspacesGetAllWorkspaceDocumentsResponseBody'
            schemes:
                - http
definitions:
    Document:
        title: Document
        type: object
        properties:
            content:
                type: string
                example: Quia commodi.
            created_at:
                type: string
                example: "2009-05-22T20:22:24Z"
                format: date-time
            id:
                type: string
                example: f03de107-ca95-4f36-9f62-9679f6271d84
                format: uuid
            title:
                type: string
                example: Est nihil et quasi molestias.
            version:
                type: integer
                example: 5981053160314408447
                format: int64
            workspace_id:
                type: string
                example: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
                format: uuid
        description: Knowledge sharing medium in this platform is a document.
        example:
            content: Quia commodi.
            created_at: "2009-05-22T20:22:24Z"
            id: f03de107-ca95-4f36-9f62-9679f6271d84
            title: Est nihil et quasi molestias.
            version: 5981053160314408447
            workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
        required:
            - id
            - title
            - version
            - content
            - workspace_id
            - created_at
    DocumentsCreateDocumentRequestBody:
        title: DocumentsCreateDocumentRequestBody
        type: object
        properties:
            title:
                type: string
                example: Voluptate et nihil quaerat sit error.
            workspace_id:
                type: string
                example: 0d5ff728-d37a-412b-8864-6ec621221ec2
                format: uuid
        example:
            title: Voluptate et nihil quaerat sit error.
            workspace_id: 0d5ff728-d37a-412b-8864-6ec621221ec2
        required:
            - title
            - workspace_id
    Workspace:
        title: Workspace
        type: object
        properties:
            created_at:
                type: string
                example: "1997-02-12T09:49:59Z"
                format: date-time
            id:
                type: string
                example: 72ea645c-b5d8-414b-a9ef-50a95d381edf
                format: uuid
            name:
                type: string
                example: Eum quo incidunt.
            owner_id:
                type: string
                example: 11e6c044-e250-4055-81fd-ba9bfda9b8df
                format: uuid
        description: Workspace is where multiple people can come and share knowledge using documents.
        example:
            created_at: "1997-02-12T09:49:59Z"
            id: 72ea645c-b5d8-414b-a9ef-50a95d381edf
            name: Eum quo incidunt.
            owner_id: 11e6c044-e250-4055-81fd-ba9bfda9b8df
        required:
            - id
            - name
            - owner_id
            - created_at
    WorkspacesCreateWorkspaceRequestBody:
        title: WorkspacesCreateWorkspaceRequestBody
        type: object
        properties:
            name:
                type: string
                example: Voluptatem corporis nemo qui dicta occaecati.
            owner_id:
                type: string
                example: 27bd44a5-6cf6-4e18-8b6b-ae8e809b4337
                format: uuid
        example:
            name: Voluptatem corporis nemo qui dicta occaecati.
            owner_id: 27bd44a5-6cf6-4e18-8b6b-ae8e809b4337
        required:
            - name
            - owner_id
    WorkspacesGetAllWorkspaceDocumentsResponseBody:
        title: WorkspacesGetAllWorkspaceDocumentsResponseBody
        type: object
        properties:
            documents:
                type: array
                items:
                    $ref: '#/definitions/Document'
                example:
                    - content: Quia commodi.
                      created_at: "2009-05-22T20:22:24Z"
                      id: f03de107-ca95-4f36-9f62-9679f6271d84
                      title: Est nihil et quasi molestias.
                      version: 5981053160314408447
                      workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
                    - content: Quia commodi.
                      created_at: "2009-05-22T20:22:24Z"
                      id: f03de107-ca95-4f36-9f62-9679f6271d84
                      title: Est nihil et quasi molestias.
                      version: 5981053160314408447
                      workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
                    - content: Quia commodi.
                      created_at: "2009-05-22T20:22:24Z"
                      id: f03de107-ca95-4f36-9f62-9679f6271d84
                      title: Est nihil et quasi molestias.
                      version: 5981053160314408447
                      workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
        example:
            documents:
                - content: Quia commodi.
                  created_at: "2009-05-22T20:22:24Z"
                  id: f03de107-ca95-4f36-9f62-9679f6271d84
                  title: Est nihil et quasi molestias.
                  version: 5981053160314408447
                  workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
                - content: Quia commodi.
                  created_at: "2009-05-22T20:22:24Z"
                  id: f03de107-ca95-4f36-9f62-9679f6271d84
                  title: Est nihil et quasi molestias.
                  version: 5981053160314408447
                  workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
                - content: Quia commodi.
                  created_at: "2009-05-22T20:22:24Z"
                  id: f03de107-ca95-4f36-9f62-9679f6271d84
                  title: Est nihil et quasi molestias.
                  version: 5981053160314408447
                  workspace_id: 60d14f46-51e6-4b7d-9bbc-a1f53ed7bc6e
