swagger: "2.0"
info:
    title: Collaborative Knowledge Platform Backenk service
    description: |4-
        	API for backend service powering Kollap platform.
        	
    version: "1.0"
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /v1/document/{id}:
        get:
            tags:
                - documents
            summary: getDocument documents
            operationId: documents#getDocument
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
                  format: uuid
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Document'
            schemes:
                - http
    /v1/workspace/create:
        post:
            tags:
                - workspaces
            summary: createWorkspace workspaces
            operationId: workspaces#createWorkspace
            parameters:
                - name: CreateWorkspaceRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/WorkspacesCreateWorkspaceRequestBody'
                    required:
                        - name
                        - owner_id
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Workspace'
                        required:
                            - id
                            - name
                            - owner_id
                            - created_at
            schemes:
                - http
definitions:
    Document:
        title: Document
        type: object
        properties:
            content:
                type: string
                example: Tempora voluptatem qui eius ipsam.
            created_at:
                type: string
                example: "1970-05-13T09:37:10Z"
                format: date-time
            id:
                type: string
                example: d00088da-f935-4c13-a4ae-1d37c5d95e09
                format: uuid
            title:
                type: string
                example: Qui nobis sunt.
            version:
                type: integer
                example: 776250283615509095
                format: int64
        description: Knowledge sharing medium in this platform is a document.
        example:
            content: Tempora voluptatem qui eius ipsam.
            created_at: "1970-05-13T09:37:10Z"
            id: d00088da-f935-4c13-a4ae-1d37c5d95e09
            title: Qui nobis sunt.
            version: 776250283615509095
    Workspace:
        title: Workspace
        type: object
        properties:
            created_at:
                type: string
                example: "1997-02-12T09:49:59Z"
                format: date-time
            id:
                type: string
                example: 72ea645c-b5d8-414b-a9ef-50a95d381edf
                format: uuid
            name:
                type: string
                example: Eum quo incidunt.
            owner_id:
                type: string
                example: 11e6c044-e250-4055-81fd-ba9bfda9b8df
                format: uuid
        description: Workspace is where multiple people can come and share knowledge using documents.
        example:
            created_at: "1997-02-12T09:49:59Z"
            id: 72ea645c-b5d8-414b-a9ef-50a95d381edf
            name: Eum quo incidunt.
            owner_id: 11e6c044-e250-4055-81fd-ba9bfda9b8df
        required:
            - id
            - name
            - owner_id
            - created_at
    WorkspacesCreateWorkspaceRequestBody:
        title: WorkspacesCreateWorkspaceRequestBody
        type: object
        properties:
            name:
                type: string
                example: Voluptatem corporis nemo qui dicta occaecati.
            owner_id:
                type: string
                example: 27bd44a5-6cf6-4e18-8b6b-ae8e809b4337
                format: uuid
        example:
            name: Voluptatem corporis nemo qui dicta occaecati.
            owner_id: 27bd44a5-6cf6-4e18-8b6b-ae8e809b4337
        required:
            - name
            - owner_id
